# Generated by Django 4.2.25 on 2025-10-30 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='描述')),
                ('material_type', models.CharField(choices=[('image', '图片'), ('vector', '矢量图'), ('psd', 'PSD模板'), ('video', '视频'), ('audio', '音频')], max_length=20, verbose_name='素材类型')),
                ('image_preview', models.ImageField(upload_to='material_previews/', verbose_name='预览图')),
                ('file', models.FileField(upload_to='materials/', verbose_name='素材文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载次数')),
                ('likes', models.IntegerField(default=0, verbose_name='收藏数')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='价格')),
                ('is_free', models.BooleanField(default=False, verbose_name='是否免费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.category', verbose_name='分类')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='materials.material')),
            ],
        ),
    ]
