# 第一行：基础镜像
FROM python:3.10-slim

# 第二行：工作目录
WORKDIR /material-site

# 第三、四行：Python 环境变量
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV DJANGO_SETTINGS_MODULE=backend.settings

# 第五行开始：安装系统依赖
#RUN apt-get update && apt-get install -y \
#    gcc \
#    default-libmysqlclient-dev \
#    pkg-config \
#    && rm -rf /var/lib/apt/lists/*

# 复制依赖文件
COPY requirements.txt .

# 安装 Python 依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目代码
COPY . .

# 创建非 root 用户（安全最佳实践）
#RUN useradd -m -u 1000 django && chown -R django:django /app
#USER django

# 暴露端口
EXPOSE 8000

# 启动命令
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:$PORT"]