# Generated by Django 4.2.25 on 2025-11-15 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="分类名称"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL标识")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="图标类名"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="material_site.category",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="标签名称"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=30, unique=True, verbose_name="URL标识"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#666666", max_length=7, verbose_name="标签颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="素材标题")),
                (
                    "slug",
                    models.SlugField(max_length=30, unique=True, verbose_name="URL标识"),
                ),
                ("description", models.TextField(blank=True, verbose_name="素材描述")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("image", "图片"),
                            ("vector", "矢量图"),
                            ("video", "视频"),
                            ("audio", "音频"),
                            ("template", "模板"),
                            ("font", "字体"),
                            ("other", "其他"),
                        ],
                        default="image",
                        max_length=20,
                        verbose_name="素材类型",
                    ),
                ),
                (
                    "main_file",
                    models.FileField(
                        upload_to="materials/%Y/%m/%d/", verbose_name="主文件"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/%Y/%m/%d/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="previews/%Y/%m/%d/",
                        verbose_name="预览图",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "dimensions",
                    models.CharField(blank=True, max_length=50, verbose_name="尺寸/分辨率"),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="时长(秒)"),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("free", "免费"),
                            ("premium", "付费"),
                            ("cc-by", "CC BY"),
                            ("cc-by-sa", "CC BY-SA"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="许可类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=8, verbose_name="价格"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已发布"),
                            ("rejected", "已拒绝"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览数")),
                ("download_count", models.IntegerField(default=0, verbose_name="下载数")),
                ("like_count", models.IntegerField(default=0, verbose_name="点赞数")),
                ("favorite_count", models.IntegerField(default=0, verbose_name="收藏数")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="material_site.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="materials",
                        to="material_site.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "素材",
                "verbose_name_plural": "素材",
                "db_table": "materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="material_site.material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "db_table": "favorites",
            },
        ),
        migrations.CreateModel(
            name="DownloadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downloaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="material_site.material",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "下载记录",
                "verbose_name_plural": "下载记录",
                "db_table": "download_history",
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["status", "material_type"], name="materials_status_11d5df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["author", "created_at"], name="materials_author__dd40d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["view_count", "download_count"],
                name="materials_view_co_f4aa5a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite", unique_together={("user", "material")},
        ),
    ]
